document.writeln("<table width=\"960\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td width=\"9\"><img src=\"http:\/\/tools.kqiqi.com\/images\/c1.gif\" width=\"9\" height=\"45\" \/><\/td>");
document.writeln("    <td width=\"931\" valign=\"top\">");
document.writeln("	");
document.writeln("	<a target=\"_blank\" href=\"http:\/\/cy.kqiqi.com\/\">");
document.writeln("	");
document.writeln("	<img border=\"0\" src=\"http:\/\/tools.kqiqi.com\/shuzi\/banner.gif\" width=\"925\" height=\"45\"><\/a><\/td>");
document.writeln("    <td width=\"20\"><img src=\"http:\/\/tools.kqiqi.com\/images\/c2.gif\" width=\"20\" height=\"45\" \/><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");