
var fc=$('c'),fk=function(s){return $r($k(s,'sk'),/%\w{2}/g,function(a){return String.fromCharCode($i('0x'+$s(a,1)))});};function domain_name(s){var h='',z=$('cs'),t='<style type="text/css">#c li{line-height:28px;height:28px}.c1 li{float:left;width:67px}.c1 li input{margin:0 3px}#cf6 li{position:relative;border-bottom:#ddd 1px dashed}#cf6 .yn{line-height:12px;width:20px}#cf6 img{margin:0 6px 0 0}#cf6 .h4r{right:0}</style>',q=function(k){return(N(k)&&(!k.match(/[^a-z0-9-]+/)&&'-'!=$s(k,0,1)))?$1:$0};function y(s){var g=$p(s,'_'),h='';if(N(g[0])){F(g,function(d){h+='<li><span><img src="http://weigeti.com/i0/loading.gif"/></span><span>.'+d+'</span><span></span><span class="h4r">如果不可以就查询whois</span></li>';})}return h}
function x(k){F($("cf6^li"),function(i){o=$("^span",i);var a=o[0],b=H(o[1]),c=o[2],d=o[3],n,j="yn yn",m,l;function f(h){n=$i($p(h,'|')[2]);if(n==210){j+=1;m='<span style="color:#093">（可以注册）</span>';l='<a href="#">立刻注册</a>'}else{if(n==211){j+=0;m='&nbsp;（已被注册）';l='<a href="#">查看Whois</a>'}else{j+=2;m='&nbsp;（查询故障）';l='<a href="#">访问网址</a>'}}H(a,"");C(a,j);H(c,m);H(d,l)}$A('http://e.v-get.com/t/domain_name.php',k+b,0,f);})}
z.onsubmit=function(){var s='',k=z.sk.value;F($('^input',fc),function(a){if(a.checked||a.checked=='checked')s+='_'+a.value});if(q(k)){H($("cf6"),y($s(s,1)));x(k);}else alert('请输入英文、数字、减号\n\n或在“站长工具”查看详细说明');return false};H(fc,t+'<div class="c1"><ul><li><input type="checkbox" checked="checked" value="com"/>.com</li><li><input type="checkbox" checked="checked" value="cn"/>.cn</li><li><input type="checkbox" checked="checked" value="com.cn"/>.com.cn</li><li><input type="checkbox" checked="checked" value="biz"/>.biz</li><li><input type="checkbox" checked="checked" value="net"/>.net</li><li><input type="checkbox" value="net.cn"/>.net.cn</li><li><input type="checkbox" checked="checked" value="co"/>.co</li><li><input type="checkbox" checked="checked" value="org"/>.org</li><li><input type="checkbox" value="org.cn"/>.org.cn</li><li><input type="checkbox" value="name"/>.name</li><li><input type="checkbox" value="info"/>.info</li><li><input type="checkbox" value="gov.cn"/>.gov.cn</li><li><input type="checkbox" value="tv"/>.tv</li><li><input type="checkbox" value="cc"/>.cc</li></ul></div><div class="o mb"></div><div><ul id="cf6">'+y($k(s,'sx'))+'</ul></div>');if(q(fk(s))){x(fk(s))};if(!$3._c)$3._c=$4.createStyleSheet();_c.cssText=t;}
function http_status(s){var k=fk(s);if(N(k)&&(k.match(/\./))){if($2!=$s(k,0,7))k=$2+k;var g='<p>网址 '+k+' 状态码：</p><p>',a;function f(h){a=$s(h,9,3);F($('f^strong'),function(o){if(a==H(o))g+=H(o.parentNode)});g+='</p><p>'+$r(h,/\|/g,'</p><p>');H(fc,g+'</p>')}
$A('http://e.v-get.com/t/http_status.php',k,0,f);}
else H(fc,'<p>请输入完整的网址，如http://e.v-get.com/tool/</p>')}
function icp_beian(s){var k=fk(s);function f(h){if(N(h)){var a=$p(h,','),r=['主办单位名称','主办单位性质','备案许可证号','网站备案名称','网站首页地址','备案审核时间'],j='<table>';F(a,function(o,i){j+='<tr><td>'+r[i]+'</td><td>'+o+'</td></tr>'});H(fc,j+'</table>');}else H(fc,'<p class="f0">未备案</p>')}
if(N(k))$A('http://e.v-get.com/t/icp_beian.php',k,0,f);H(fc,'<p class="f0">请输入域名，如v-get.com</p>')}
function ip_address(s){var k=fk(s);function f(h){if(N(h))H(fc,'<p class="f6">获得IP地址：'+h+'</p>');else H(fc,'<p class="f0">未检测到IP</p>')}
if(N(k)&&(k.match(/\./))){$A('http://e.v-get.com/t/ip_address.php',k,0,f)}else H(fc,'<p>请输入完整的网址，如http://e.v-get.com/</p>')}
function alexa_rank(s){var k=fk(s);function f(h){var a=[],b=['国家','国内排名','世界排名','排名变化','反链数量'],t='</tr>',s='<tr>',z=s;a[0]=$r($r(h,/.+COUNTRY[^>]+NAME="([^"]+)".+/g,'$1'),'China','中国');a[1]=$r(h,/.+COUNTRY[^>]+RANK="(\d+)".+/,'$1');a[2]=$r(h,/.+POPULARITY[^>]+TEXT="(\d+)".+/,'<strong class="f0">$1</strong>');a[3]=$r(h,/.+RANK[^>]+DELTA="([-+]?\d+)".+/,'$1');a[4]=$r(h,/.+LINKSIN[^>]+NUM="(\d+)".+/,'$1');F(a,function(x,i){z+='<th>'+b[i]+'</th>';s+='<td>'+x+'</td>'});H(fc,'<table>'+z+t+s+t+'</table>')}if(N(k)&&(k.match(/\./)))$A('http://e.v-get.com/t/alexa_rank.php',k,0,f);else H(fc,'<p>请输入域名，如v-get.com</p>')}
function google_pr(s){var k=fk(s),y,r,j;if($2==$s(k,0,7))k=$r(k,$2,'');function f(h){r=$r(h,/^Rank_1:1:(\d).+/,'$1');r=L(r)==1?r:'0';function l(p){return L(h.match(RegExp('<a[^>]+href="http:\/\/'+p+'[^>]+>','g')))}
j=l('')-l($p(k,'/')[0]);H(fc,'PR：'+r+'；外链：'+j+'；PR输出值：'+(l('')>0?(0.15+0.85*(r/(j?j:1))):0));}
if(N(k)&&(k.match(/\./)))$A('http://e.v-get.com/t/google_pr.php',k,0,f);else H(fc,'<p>请输入域名，如e.v-get.com</p>')}
function ico_maker(){D($('cs'));H(fc,'<embed src="http://www.v-get.com/www.v-getimg.com/i1/s8/ico_maker.swf" quality="high" pluginspage="http://www.adobe.com/go/getflashplayer" play="false" loop="false" scale="exactfit" wmode="window" devicefont="false" bgcolor="#ffffff" name="iconMaker" menu="false" allowfullscreen="false" allowscriptaccess="sameDomain" salign="" type="application/x-shockwave-flash" align="middle" width="600" height="350">');}
function code_md5(s){J('http://e.v-get.com/t/code_md5.js',function(){var k=fk(s);H(fc,str2binl(k)+'<hr>'+MD5(k,8)+'<hr>'+hex_md5(k,0)+'<hr>'+hex_md5(k,1))})}
function ascii_code(s){D(fc.parentNode.parentNode);D($("f^div")[0],1);H($("f^a.h4r")[0],'关闭')}