use_frameworks!
platform :ios, '8.0'

pod 'Alamofire'
pod 'AlamofireImage'

pod 'Gifu'
pod 'HanekeSwift'
pod 'SwiftyJSON'
pod 'OAuthSwift'


#pod 'Chatto', :git => 'https://github.com/badoo/Chatto'
#pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto'

## Storage
#pod 'RealmSwift'
