<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>站长百科 网站建设与SEO优化百科全书_E维科技_V-Get!</title>
<meta name="keywords" content="站长之家 站长百科 建站百科 SEO 网站建设"/><meta name="description" content="E维科技站长百科涵盖网站建设、优秀的SEO搜索引擎优化技巧、Linux/SSH服务器配置、域名查询注册、网站配置、网站安全等互联网技术。E维科技，互联网营销专家！"/>
<link href="http://www.v-get.com/www.v-getimg.com/i0/i.ico" type="image/ico" rel="shortcut icon" />
<link href="http://www.v-get.com/www.v-getimg.com/i0/i.css" rel="stylesheet" type="text/css"  />
<link href="http://www.v-get.com/www.v-getimg.com/i0/s8/i.css" rel="stylesheet" type="text/css"  />
<link rel="stylesheet" type="text/css" href="http://www.v-get.com/www.v-getimg.com/i0/s8/ir.css" />
<script type="text/javascript" src="http://www.v-get.com/www.v-getimg.com/i0/i.js"></script>
</head>
<body><div class="ww"><div class="t"><strong>您好，<a href="#">V-Get!</a></strong><span><a href="http://www.v-get.com/"><img src="http://www.v-get.com/www.v-getimg.com/i0/g/ft1.gif"/></a>|<a href="#">代理分销</a>|<a href="http://e.v-get.com/web/">网站建设</a>|<a href="http://e.v-get.com/help/">帮助中心</a>|<a href="http://s.v-get.com/l?l=wpa.qq.com%2fmsgrd%3fv%3d3%26uin%3d921923988%26site%3dqq%26menu%3dyes">客户服务</a></span></div>
<div class="w"><div class="u"><div class="p i"><img src="http://www.v-get.com/www.v-getimg.com/i0/s8/i.gif" width="234" height="60" alt="网站建设_SEO搜索引擎关键词排名优化_义乌网站建设"/></div>
<div class="q g"><div class="s"><form action="#"><div class="p"><input type="radio" name="st" checked="checked"/><label>新闻</label><input type="radio" name="st"/><label>软件</label></div><div class="q"><input type="text" placeholder="请输入关键词" class="sk" name="sk"/><input class="ss" type="submit" value=""/></div></form></div></div><div class="o"></div></div>
<div id="n"><div class="a na"><a href="http://e.v-get.com/">首页</a><i></i><a href="http://e.v-get.com/host/">主机域名</a><i></i><a href="http://e.v-get.com/web/">网站建设</a><i></i><a href="http://e.v-get.com/office/">云端办公</a><i></i><a href="http://e.v-get.com/sem/">网络营销</a><i></i><a href="http://e.v-get.com/vi/">视觉设计</a><i></i><a href="http://e.v-get.com/soft/">软件开发</a><i></i><a href="http://e.baike.v-get.com/internet/index_1.html" class="no">网站百科</a><i></i><a href="http://e.v-get.com/tool/">站长工具</a></div>
<div class="o po">
<div class="n"></div>
<div class="n n1"><div class="p nl"><h3><a href="#">域名服务</a></h3><ul><li><a href="http://e.v-get.com/host/domain.html">域名注册查询</a></li><li><a href="http://e.v-get.com/host/icp_beian.html">工信部域名备案</a></li><li><a href="http://e.v-get.com/host/domain.html">域名隐私保护</a></li><li><a href="http://e.v-get.com/host/domain.html">二手域名转让</a></li></ul><h3><a href="#">主机服务</a></h3><ul><li><a href="http://e.v-get.com/host/cloud.html">标准云主机</a></li><li><a href="http://e.v-get.com/host/vps.html">VPS主机</a></li><li><a href="http://e.v-get.com/host/virtual.html">FTP虚拟主机</a></li><li><a href="http://e.v-get.com/host/server.html">服务器托管</a></li><li><a href="http://e.v-get.com/host/free.html">免费主机</a></li></ul></div><div class="p nr"><h3><a href="#">域名空间选购</a></h3><ul><li><a href="http://e.v-get.com/host/domain.html">怎么注册到好的域名？</a></li><li><a href="http://e.v-get.com/host/icp_beian.html">网站备案是怎么一回事？</a></li><li><a href="http://e.v-get.com/host/domain.html">二级域名是什么？</a></li><li><a href="http://e.v-get.com/host/domain.html">什么样的主机才适合我？</a></li><li><a href="http://e.v-get.com/host/domain.html">香港虚拟主机不用备案吗？</a></li><li><a href="http://e.v-get.com/host/domain.html">FTP服务器租用和托管的区别？</a></li></ul><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/inh1.jpg" alt="域名是什么" width="80" height="76"/></dt><dd><h4><a href="#">域名是什么？</a></h4><p>域名空间两者不可分离，域名是网络地址。</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
<div class="n n2"><div class="p nl"><h3><a href="#">企业展示站</a></h3><ul><li><a href="http://e.v-get.com/web/service_b1.html">B1 企业超值网站</a></li><li><a href="http://e.v-get.com/web/service_b2.html">B2 企业标准网站</a></li><li><a href="http://e.v-get.com/web/service_b3.html">B3 企业专业网站</a></li><li><a href="http://e.v-get.com/web/service_b5.html">B5 企业高级定制</a></li></ul><h3><a href="#">商城建站</a></h3><ul><li><a href="#">S1 第三方结算商城</a></li><li><a href="#">S2 标准商城建设</a></li><li><a href="#">S3 外贸商城建设</a></li></ul><h3><a href="#">优惠建站产品</a></h3><ul><li><a href="http://e.v-get.com/web/service_a1.html">A1 免费建站</a></li><li><a href="http://e.v-get.com/web/service_a2.html">A2 速成美站</a></li><li><a href="http://e.v-get.com/web/service_a3.html">A3 公司建站</a></li></ul></div><div class="p nr"><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/inw1.jpg" alt="企业网站建设" width="80" height="76"/></dt><dd><h4><a href="#">展示型网站建设？</a></h4><p>用于展示企业形象和文化相关的企业建站服务</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl><div class="o mh"></div><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/inw2.jpg" alt="商城网站建设" width="80" height="76"/></dt><dd><h4><a href="#">商城网站设计？</a></h4><p>网上购物平台产品营销与销售的建站产品</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl><div class="o mh"></div><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/inw3.jpg" alt="免费建站" width="80" height="76"/></dt><dd><h4><a href="#">免费建站？</a></h4><p>一般免费建站是指靠放置广告盈利的网站建设</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
<div class="n n3"><div class="p nl"><h3><a href="#">E维员工</a></h3><ul><li><a href="http://e.v-get.com/office/">专业客服托管</a></li><li><a href="http://e.v-get.com/office/">云办公室</a></li><li><a href="http://e.v-get.com/office/">专业客服托管</a></li></ul></div><div class="p nr"><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/ino1.jpg" alt="E维云办公" width="80" height="76"/></dt><dd><h4><a href="#">E维云办公？</a></h4><p>云端办公增强了创业者SOHO一族公司形象</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
<div class="n n4"><div class="p nl"><h3><a href="#">广告合作商</a></h3><ul><li><a href="http://e.v-get.com/sem/">百度推广代理</a></li><li><a href="http://e.v-get.com/sem/">谷歌Adword</a></li><li><a href="http://e.v-get.com/sem/">网站联盟广告</a></li></ul><h3><a href="#">搜索引擎优化</a></h3><ul><li><a href="http://e.v-get.com/sem/">SEO标准套餐</a></li><li><a href="http://e.v-get.com/sem/">SEO高级套餐</a></li><li><a href="http://e.v-get.com/sem/">外链平台</a></li><li><a href="http://e.v-get.com/sem/">软文软推</a></li></ul></div><div class="p nr"><h3><a href="#">搜索引擎优化</a></h3><ul><li><a href="http://e.v-get.com/host/domain.html">搜索引擎优化方法有哪些？</a></li><li><a href="http://e.v-get.com/host/domain.html">怎么影响搜索引擎优化排名？</a></li><li><a href="http://e.v-get.com/host/domain.html">什么是网络营销？</a></li><li><a href="http://e.v-get.com/host/domain.html">网络营销策划对企业的帮助</a></li></ul><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/ins1.jpg" alt="网络营销方案" width="80" height="76"/></dt><dd><h4><a href="#">网络营销方案</a></h4><p>网络营销的特点是：成本低、效率高、效果好</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
<div class="n n5"><div class="p nl"><h3><a href="#">摄影工作室</a></h3><ul><li><a href="http://e.v-get.com/sem/">婚庆摄影套餐</a></li><li><a href="http://e.v-get.com/sem/">艺术照摄影</a></li><li><a href="http://e.v-get.com/sem/">证件照摄影</a></li></ul><h3><a href="#">图片专业设计</a></h3><ul><li><a href="http://e.v-get.com/vi/">企业视觉设计</a></li><li><a href="http://e.v-get.com/sem/">网店图片PS套餐</a></li><li><a href="http://e.v-get.com/sem/">单张图片PS</a></li><li><a href="http://e.v-get.com/sem/">照片修复</a></li></ul></div><div class="p nr"><h3><a href="#">域名空间选购</a></h3><ul><li><a href="http://e.v-get.com/host/domain.html">二级域名是什么？</a></li><li><a href="http://e.v-get.com/host/domain.html">什么样的主机才适合我？</a></li><li><a href="http://e.v-get.com/host/domain.html">香港虚拟主机不用备案吗？</a></li><li><a href="http://e.v-get.com/host/domain.html">FTP服务器租用和托管的区别？</a></li></ul><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/inv1.jpg" alt="企业视觉设计" width="80" height="76"/></dt><dd><h4><a href="#">企业视觉设计</a></h4><p>VI设计有利于员工归属感和对外企业形象宣传</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
<div class="n n6"></div>
<div class="n n7"><div class="p nl"><h3><a href="#">技术人员专题</a></h3><ul><li><a href="http://e.v-get.com/office/">互联网资讯</a></li><li><a href="http://e.v-get.com/office/">网站百科</a></li><li><a href="http://e.v-get.com/office/">站长之家论坛</a></li></ul></div><div class="p nr"><dl><dt><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/inb1.jpg" alt="站长之家 网站百科" width="80" height="76"/></dt><dd><h4><a href="#">站长之家</a></h4><p>倾心为站长提供最全面的网站建设百科知识</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
<div class="n n8"><div class="p nl"><h3><a href="#">网站优化工具</a></h3><ul><li><a href="http://e.v-get.com/tool/domain_name.html">域名注册查询</a></li><li><a href="http://e.v-get.com/tool/http_status.html">HTTP状态码查询</a></li><li><a href="http://e.v-get.com/tool/alexa_rank.html">网站Alexa排名</a></li><li><a href="http://e.v-get.com/tool/keyword_bd.html">百度关键词排名</a></li><li><a href="http://e.v-get.com/tool/domain_whois.html">域名Whois查询</a></li><li><a href="http://e.v-get.com/tool/google_pr.html">PR值查询</a></li><li><a href="http://e.v-get.com/tool/icp_beian.html">ICP备案查询</a></li><li><a href="http://e.v-get.com/tool/ascii_code.html">ASCII编码转换</a></li></ul></div><div class="p nr"><dl><dt><a href="http://e.v-get.com/tool/alexa_rank.html"><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/int1.jpg" alt="Alexa排名查询" width="80" height="76"/></a></dt><dd><h4><a href="http://e.v-get.com/tool/alexa_rank.html">网站Alexa排名</a></h4><p>是目前用来评价某一网站访问量的一个指标</p><p class="fq"><a href="#">查询详情&gt;&gt;</a></p></dd></dl><div class="o mh"></div><dl><dt><a href="http://e.v-get.com/tool/keyword_bd.html"><img src="http://www.v-get.com/www.v-getimg.com/i1/s8/int2.jpg" alt="百度关键词排名" width="80" height="76"/></a></dt><dd><h4><a href="e.v-get.com/tool/keyword_bd.html">百度关键词排名</a></h4><p>查看网站在中国最大的搜索引擎的关键词排名</p><p class="fq"><a href="e.v-get.com/tool/keyword_bd.html">查询详情&gt;&gt;</a></p></dd></dl></div><div class="o"></div></div>
</div>
</div>
<div class="m mb">当前位置：<a href="http://e.v-get.com/">E维科技</a> &gt;&gt; 网站百科</div>
<div class="v">
<div class="p f l"><div class="lv" id="d"><h4 class="lh">主机域名</h4><ul><li><a href="http://e.v-get.com/host/domain.html">域名注册查询</a></li><li><a href="http://e.v-get.com/host/free.html">免费虚拟主机</a></li><li><a href="http://e.v-get.com/host/virtual.html">FTP服务器空间</a></li><li><a href="http://e.v-get.com/host/vps.html">VPS主机服务器</a></li><li><a href="http://e.v-get.com/host/cloud.html">传统独享云主机</a></li><li><a href="http://e.v-get.com/host/server.html">服务器托管租用</a></li><li><a href="http://e.v-get.com/host/icp_beian.html">工信部域名备案</a></li></ul></div><div class="lc"><h4>购买流程</h4><ul><li><a href="http://e.v-get.com/web/service.html">a. 客户选择主机类型</a></li><li class="lc2"></li><li><a href="http://e.v-get.com/host/domain.html">b. 联系客服付费</a></li><li class="lc2"></li><li><a href="http://e.v-get.com/host/">c. 获取主机账号</a></li><li class="lc2"></li><li><a href="http://e.v-get.com/web/service_b2.html">d. 查询使用指南</a></li></ul></div><div class="lv mb"><h4>帮助中心</h4><ul><li><a href="#">域名注册与查询教程</a></li><li><a href="#">E维科技域名过户流程</a></li><li><a href="#">主机 域名绑定 图文教程</a></li><li><a href="#">什么叫域名的泛解析</a></li><li><a href="#">注册域名时需要注重的几个...</a></li><li><a href="#">域名的相关基础知识</a></li><li><a href="#">关于查看域名A记录，MX记录...</a></li><li><a href="#">域名解析详细教程</a></li><li><a href="#">域名转入我司的流程</a></li><li><a href="#">域名解析后多长时间能用</a></li></ul></div><div><h4>帮助中心</h4><div id="lii"><p><a href="#">最新优惠</a><a href="#">付款方式</a></p><p class="lic"><a href="#">帮助中心</a><a href="#">加盟合作</a></p><p><a href="#">相关下载</a><a href="#">服务指南</a></p><p class="lic"><a href="#">故障报修</a><a href="#">备案认证</a></p>
</div></div></div>
<div class="q r">
<div class="mb"><script type="text/javascript">var cpro_id = "u1163355";</script><script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script></div>
<?php 
$Qc=mysql_connect('localhost','bk020vgt','VGTmm_258_v');mysql_select_db('v2',$Qc);mysql_query('set names utf8');
$p=empty($_GET['p'])?1:$_GET['p'];$P=($p-1)*20;
echo '<div class="f"><h4>网站百科</h4><div class="mf">';
$Qy=mysql_query("SELECT COUNT(*) FROM f WHERE s=8");
$Qq=mysql_query("SELECT * FROM f WHERE s=8 ORDER BY t DESC LIMIT $P,20");
$Qz=mysql_fetch_array($Qy);
$Iz=$Qz[0];$Pz=ceil($Iz/20);$pg='';
if($Pz>1){
$Pp=$p-1;$Pn=$p+1;
$Pq=($Pp==1)?'':'_'.$Pp;
switch ($p)
{ case 1:$pg='<div class="vbk_pg fq"><a class="po">首页</a><a class="po">前一页&lt;</a>第<b>1</b>页<a href="http://e.baike.v-get.com/?p=2" target="_self">&gt;下一页</a><a href="http://e.baike.v-get.com/?p=2'.$Pz.'" target="_self">共'.$Pz.'页</a></div>';break;
 case $Pz:$pg='<div class="pg"><a href="http://e.baike.v-get.com/" target="_self">首页</a><a href="http://e.baike.v-get.com/?p='.$Pp.'" target="_self">前一页&lt;</a>第<b>'.$p.'</b>页<a class="po">&gt;下一页</a><a class="po">第'.$p.'页</a></div>';break;
  default:$pg='<div class="pg"><a href="http://e.baike.v-get.com/" target="_self">首页</a><a href="http://e.baike.v-get.com/?p='.$Pp.'" target="_self">前一页&lt;</a>第<b>'.$p.'</b>页<a href="http://e.baike.v-get.com/?p='.$Pn.'" target="_self">&gt;下一页</a><a href="http://e.baike.v-get.com/?p=2'.$Pz.'" target="_self">第'.$Pz.'页</a></div>';break;
}}
else $pg='<div class="pg"></div>';

echo $pg,'<div id="c" class="vb0c">';

while($r=mysql_fetch_array($Qq)){
$I=$r['i'];
echo '<div><h2><a href="http://baike.v-get.com/view/',$I,'.html?l=e.">',$r['h'],'</a><span>',$r['t'],'</span></h2><p>',$r['d'],'<a href="http://www.google.com.hk/search?hl=zh-CN&domains=v-get.com&sitesearch=v-get.com&ie=utf-8&q=',$r['k'],'&x=0&y=0">相似阅读</a></p></div>';
}mysql_close($Qc);
echo '</div>',$pg,'</div></div>';
?>
</div>
<div class="o mh"></div>
<div class="vb mb"><ul><li><h4><a href="http://e.v-get.com/web/service.html">建站产品</a></h4><p><a href="http://e.v-get.com/host/domain.html">免费域名注册</a></p><p><a href="http://e.v-get.com/host/">服务器空间租用</a></p><p><a href="http://e.v-get.com/web/service.html">免费网站建设</a></p><p><a href="http://e.v-get.com/web/service.html">企业级网站建设</a></p><p><a href="http://e.v-get.com/web/service.html">B2B/B2C商城网站</a></p><p><a href="http://e.v-get.com/web/service.html">定制型企业建站</a></p></li><li><h4><a href="http://e.v-get.com/web/service.html">优惠活动</a></h4><p><a href="http://e.v-get.com/issue/godaddy.html">Godaddy优惠码</a></p><p><a href="http://e.v-get.com/issue/godaddy.html">建站产品优惠码</a></p><p><a href="http://e.v-get.com/issue/godaddy.html">SEO优化折扣中心</a></p><p><a href="http://e.v-get.com/issue/godaddy.html">竞价排名优惠码</a></p></li><li><h4><a href="#">附加功能</a></h4><p><a href="http://e.v-get.com/web/">Flash特效制作</a></p><p><a href="http://e.v-get.com/web/">会员管理系统</a></p><p><a href="http://e.v-get.com/web/">JS动态效果制作</a></p><p><a href="http://e.v-get.com/web/">Banner广告条制作</a></p></li><li><h4><a href="http://e.v-get.com/web/">常见问题</a></h4><p><a href="http://e.v-get.com/web/">如何操作域名解析</a></p><p><a href="http://e.v-get.com/web/">如何对域名备案</a></p><p><a href="http://e.v-get.com/web/">如何转移域名商</a></p><p><a href="http://e.v-get.com/web/">如何使用优惠码</a></p></li><li><h4><a href="http://e.v-get.com/web/">站长之家</a></h4><p><a href="http://e.v-get.com/web/">网站建设站长工具</a></p><p><a href="http://e.v-get.com/web/">站长素材与软件</a></p><p><a href="http://e.v-get.com/web/">SEO优化在线查询</a></p><p><a href="http://e.v-get.com/web/">网站管理者论坛</a></p></li></ul><div class="o"></div></div>
</div>
<div class="b"><p class="bn"><a href="#">关于我们</a>|<a href="#">联系我们</a>|<a href="#">合作分销</a>|<a href="#">人才招聘</a>|<a href="#">网上兼职</a>|<a href|<a href="#">合作加盟</a>|<a href="#">广告服务</a>|<a href="#">合作伙伴</a>|<a href="#">E维公益</a>|<a href="#">投诉建议</a>|<a href="#">网站地图</a>|<a href="#">法律声明</a></p><p>互联网信息服务资格证 2012-0033 | 网络文化经营许可证 文网文[2012]040号| 信息网络传播视听节目许可证 11093913号</p><p>ICP备12013909号 | 增值电信与信息服务业务经营许可证 | 服务热线:0579-85577543</p><p>Copyright &copy; 2008-2013<a href="http://www.v-get.com/">V-Get.com</a>All Rights Reserved. E维科技 版权所有</p><div class="ba a"><a href="http://s.v-get.com/l?l=gsj.zj.gov.cn"></a><a href="http://s.v-get.com/l?l=www.cnnic.cn"><a href="http://s.v-get.com/l?l=www.ywga.gov.cn"></a><a href="http://s.v-get.com/l?l=www.szfw.org"></a></div></div></div></div>
<div class="pn"><script type="text/javascript">J('http://www.v-get.com/www.v-getimg.com/i0/s8/i.js');var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F1647779f45896943c60c75fb905f6360' type='text/javascript'%3E%3C/script%3E"));</script></div>
<script type="text/javascript">var cpro_id = "u1132441";</script><script src="http://cpro.baidustatic.com/cpro/ui/f.js" type="text/javascript"></script>
</body></html>