<?php
define('UC_CONNECT','mysql');
define('UC_DBHOST','localhost');
define('UC_DBUSER','LGoe2301Do');
define('UC_DBPW','eoLo30DNekD02');
define('UC_DBNAME','vi');
define('UC_DBCHARSET','utf8');
define('UC_DBTABLEPRE','`vi`.uc_');
define('UC_DBCONNECT',0);
define('UC_CHARSET','utf-8');
define('UC_KEY','JevaS7N2i6GbO6o7e8feX4N0V7gcw4p1G8Jd0bW7H8peM7e8E4p1Z8E6J3h8qaqc');
define('UC_API','http://i.v-get.com/sso');
define('UC_APPID','1');
define('UC_IP','223.4.239.68');
define('UC_PPP',20);