disabled_rules: # rule identifiers to exclude from running
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - todo
  - type_body_length
  - variable_name
  - variable_name_min_length
  - variable_name_max_length
  - type_name
