<?php 
$SK=$_GET['sk']; $SK=preg_replace('/[\\\'\"=\(\);]/',' ',$SK); if(empty($SK)){header('Location: http://e.v-get.com');exit();}if(!isset($_GET['ie'])||'utf-8'!=$_GET['ie']){ $is_utf8=preg_match('/^([\xE4-\xE9][\x80-\xBF]{2})|([\xE4-\xE9][\x80-\xBF]{2}){2,}|([\xE4-\xE9]{1}[\x80-\xBF]{2})$/',$SK); $SK=$is_utf8?$SK:iconv($encode,'UTF-8',$SK);}$sp=empty($_GET['sp'])?1:(int)$_GET['sp'];$Qp=($sp-1)*10;
$SE=isset($_GET['se'])&&'w3c'==$_GET['se']?'w3c':'';
$allSE=($SE=='')?true:false;
?><!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><link href="http://tu.v-get.com/i.css" rel="stylesheet" type="text/css"  /><link href="http://tu.v-get.com/s.css" rel="stylesheet" type="text/css"  /><?php echo '<title>',$SK,'_E维科技_V-Get!</title><link href="http://e.v-get.com/s?',($allSE?'':('se='.$SE.'&')),'sk=',str_replace(array('+',' '),array('%2B','%20'),$SK),'" rel="canonical" /><meta name="keywords" content="'.$SK.'"/>';?></head><body><div class="ws"><div class="ts"></div><div class="s"><form action="http://e.v-get.com/s"><input type="hidden" name="ie" value="utf-8"><?php echo $allSE?'':('<input type="hidden" name="se" value="'.$SE.'">');?><span class="skw"><input type="text" name="sk" class="sk" value="<?php echo $SK;?>"></span><span class="ssw"><input id="ss" type="submit" value="E维科技"></span></form></div><br><div class="v"><div class="p l"><div id="c"><?php 

if($allSE){
$QC=mysql_connect('localhost','Atc23ODw0d','E2Y0u3lVpg0x');mysql_select_db('ve',$QC);mysql_query('set names utf8');
$Qq=mysql_query('(SELECT i,h,d,g,t FROM f2013 WHERE h LIKE "%'.$SK.'%" OR k LIKE "%'.$SK.'%") UNION (SELECT i,h,d,g,t FROM (SELECT i,h,d,g,t FROM f2013 WHERE d LIKE "%'.$SK.'%" OR f LIKE "%'.$SK.'%" ORDER BY t DESC) f2013) LIMIT '.$Qp.',10',$QC);
$Qy=mysql_query('SELECT COUNT(*) FROM f2013 WHERE h LIKE "%'.$SK.'%" OR f LIKE "%'.$SK.'%"');
while($Qa=mysql_fetch_array($Qq)){$T=$Qa['t'];$t=strtotime($T);$t=date('Ymd/His',$t);$G=$Qa['g'];echo '<h2><a href="http://e.v-get.com/tech/top',$G,'_1.html" class="fg',$G,'"></a><a href="http://e.v-get.com/tech/',$t,$Qa['i'],'.html">',$Qa['h'],'</a><i>',$T,'</i></h2><p>',$Qa['d'],'</p>';}
}
else {
$QC=mysql_connect('localhost','i0oRvne8l2j1Vm','w3GeTxOgI0oq');mysql_select_db('ve',$QC);mysql_query('set names utf8');
$Qq=mysql_query('(SELECT l,h,d FROM w3c WHERE a ="$SK") UNION (SELECT l,h,d FROM w3c WHERE x LIKE "%'.$SK.'%" OR h LIKE "%'.$SK.'%" OR g LIKE "%'.$SK.'%" OR k LIKE "%'.$SK.'%") UNION (SELECT l,h,d FROM w3c WHERE d LIKE "%'.$SK.'%" OR f LIKE "%'.$SK.'%" OR g LIKE "%'.$SK.'%") LIMIT '.$Qp.',10',$QC);
$Qy=mysql_query('SELECT COUNT(*) FROM w3c WHERE h LIKE "%'.$SK.'%" OR f LIKE "%'.$SK.'%"');
while($Qa=mysql_fetch_array($Qq)){echo '<h2><a href="http://e.v-get.com/w3c/',$Qa['l'],'.html">',$Qa['h'],'</a></h2><p>',$Qa['d'],'</p>';}
}
$Qz=mysql_fetch_array($Qy);$Qt=$Qz[0];$Pz=ceil($Qt/10);
echo '<div class="o mh mg"></div>'; if($Pz>1){ switch ($sp){ case 1:echo '<div class="pg"><a class="po">首页</a><a class="po">前一页&lt;</a>第<i>1</i>页<a href="http://e.v-get.com/s?sk=',$SK,'&sp=',($sp+1),'" target="_self">&gt;下一页</a><a href="http://e.v-get.com/s?sk=',$SK,'&sp=',$Pz,'" target="_self">共',$Pz,'页</a></div>';break; case $Pz:echo '<div class="pg"><a href="http://e.v-get.com/s?sk=',$SK,'" target="_self">首页</a><a href="',($sp>2?('http://e.v-get.com/s?sk='.$SK.'&sp='.($sp-1)):('http://e.v-get.com/s?sk='.$SK)),'" target="_self">前一页&lt;</a>第<i>',$sp,'</i>页<a class="po">&gt;下一页</a><a class="po">第<i>',$sp,'</i>页</a></div>';break; default:echo '<div class="pg"><a href="http://e.v-get.com/s?sk=',$SK,'" target="_self">首页</a><a href="',($sp>2?('http://e.v-get.com/s?sk='.$SK.'&sp='.($sp-1)):('http://e.v-get.com/s?sk='.$SK)),'" target="_self">前一页&lt;</a>第<i>',$sp,'</i>页<a href="http://e.v-get.com/s?sk=',$SK,'&sp=',($sp+1),'" target="_self">&gt;下一页</a><a href="http://e.v-get.com/s?sk=',$SK,'&sp=',$Pz,'" target="_self">第<i>',$Pz,'页</i></a></div>';break; } } ?></div></div><div class="q r"></div></div><div class="o mh"></div><div class="s"><form action="http://e.v-get.com/s"><input type="hidden" name="ie" value="utf-8"><?php echo $allSE?'':('<input type="hidden" name="se" value="'.$SE.'">');?><span class="skw"><input type="text" name="sk" class="sk" value="<?php echo $SK;?>"></span><span class="ssw"><input id="ss" type="submit" value="E维科技"></span></form></div></div><div class="pn"><script type="text/javascript" src="http://tu.v-get.com/i.js"></script><script type="text/javascript">E($("ss"),"mousedown",function(){SP(this,-100,0);});E($("ss"),$9,function(){SP(this,0,0);});var _bdhmProtocol=(("https:"== document.location.protocol)?" https://":" http://");document.write(unescape("%3Cscript src='"+_bdhmProtocol+"hm.baidu.com/h.js%3F2cdfc5c1af66f6603163203248653a5e' type='text/javascript'%3E%3C/script%3E"));</script></div></body></html>