<?php
$url = $_SERVER['PHP_SELF']; 
$filename= substr( $url , strrpos($url , '/')+2,-4); 
if(!isset($_GET['sure'])){
echo '<a href="?sure=ok">确定更新'.$filename.'.php?</a>';
exit;
}
require '../_/co.php';
$file=constant('uploadFile').'/co/'.$filename.'.php';
$fp=fopen($file,'w+');if(is_writable($file)==false) {die("文件没有找到");exit;}
else{
$text='<?php '.constant('CO_SQL').'$bl=false;$iH=\'\';$iD=\'\';if(isset($_GET[\'show\'])){$iP=$_GET[\'show\'];$iX=1;$IX=\'_\';if(empty($_GET[\'i\'])){$iX=0;$IX=\'\';}if($iP==0){header(\'HTTP/1.1 301 Moved Permanently\');if($iX==0){header(\'Location: http://'.constant('localhost').'\'.$E.\'.wuliu.v-get.com/logistics/exhibition.html\');}else {header(\'Location: http://'.constant('localhost').'\'.$E.\'.wuliu.v-get.com/logistics/services.html\');}exit();}$Qqi=mysql_query(\'SELECT * FROM coi WHERE e="\'.$E.\'" AND p=\'.$iP.\' AND x=\'.$iX.\' LIMIT 1\');$Qqr=mysql_num_rows($Qqi);if($Qqr==0){if($iX==0){header(\'Location: http://'.constant('localhost').'\'.$E.\'.wuliu.v-get.com/logistics/exhibition.html\');}else {header(\'Location: http://'.constant('localhost').'\'.$E.\'.wuliu.v-get.com/logistics/services.html\');}exit();}$Qai=mysql_fetch_array($Qqi);$bl=true;$iH=$Qai[\'h\'];$iD=$Qai[\'d\'];}$Qq=mysql_query(\'SELECT b,h,he,k,d,r,q,lt,x,y,z,zz,t,adt,tj FROM co WHERE e="\'.$E.\'" LIMIT 1\');$Qr=mysql_num_rows($Qq);if($Qr==0){header(\'Location: http://wuliu.v-get.com/\');exit();}$Qa=mysql_fetch_array($Qq);$B=$Qa[\'b\'];$H=$Qa[\'h\'];$K=$Qa[\'k\'];$Z=$Qa[\'z\'];$LT=$Qa[\'lt\'];$TA=$Qa[\'adt\'];$now=time();$ad=($TA>$now)?false:true;echo \'<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><title>\',$iH,\' \',$H,\'展厅_\',$Z,$K,\'_商务物流网_V-Get!</title><meta name="keywords" content="\',$K,\'" /><meta name="description" content="\',$iD,$Qa[\'d\'],$Z,\'就选\',$H,\'"/>\';?>'.COTUN($filename).'<div class="q r"><div class="o mh"></div><div class="m cc"><div>您现在的位置：<?php echo \'<a href="http://\',$E,\'.wuliu.v-get.com/">\',$H,\'</a>\';?> &gt; 视觉展厅</div></div><?php if($bl){echo \'<div class="cc cit"><h2>\',$iH,\'</h2></div><div class="po ii f"><div class="iii ho"><img src="http://'.constant('localhost').'tp.v-get.com/j/3/co/600/\',$E,$IX,$iP,\'.jpg" alt="\',$iD,\'"/></div><div class="iia pr a"><a href="http://'.constant('localhost').'\',$E,\'.wuliu.v-get.com/logistics/exhibition.html?i=\',$iX,\'&show=\',($iP-1),\'" class="iil" target="_self"></a><a href="http://'.constant('localhost').'\',$E,\'.wuliu.v-get.com/logistics/exhibition.html?i=\',$iX,\'&show=\',($iP+1),\'" class="iir" target="_self"></a><div class="o"></div></div></div><div class="o mh"></div><div class="cib"><p>\',$iD,\'</p></div>\';}else {echo \'<div class="a ca">\';$Qqi=mysql_query(\'SELECT * FROM coi WHERE e="\'.$E.\'" AND x=0\');while($Qai=mysql_fetch_array($Qqi)){$iP=$Qai[\'p\'];$iH=$Qai[\'h\'];echo \'<a href="http://'.constant('localhost').'\',$E,\'.wuliu.v-get.com/logistics/exhibition.html?show=\',$iP,\'"><img src="http://'.constant('localhost').'tp.v-get.com/j/3/co/205x110/\',$E,$Qai[\'p\'],\'.jpg" width="205" height="110" alt="\',$iH,\'"/><br>\',$iH,\'<br>\',$Qai[\'d\'],\'</a>\';}echo \'</div><div class="o"></div>\';}?></div><div class="o mh"></div>'.constant('CO_VBB');
file_put_contents($file,$text);}
?>